// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyesWQRXFJ8-qZ36mWeY6pbU-oKI1s1u4',
    appId: '1:138811229758:web:d9abcfcdae3adcf3ae336f',
    messagingSenderId: '138811229758',
    projectId: 'gajeep-c5101',
    authDomain: 'gajeep-c5101.firebaseapp.com',
    databaseURL: 'https://gajeep-c5101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gajeep-c5101.appspot.com',
    measurementId: 'G-F47EHB16WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnkaLr9-BnWw_JFJkELPlW6Rn8EaemFk',
    appId: '1:138811229758:android:7f59f6d22112ca29ae336f',
    messagingSenderId: '138811229758',
    projectId: 'gajeep-c5101',
    databaseURL: 'https://gajeep-c5101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gajeep-c5101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-OoRnuxa_4qTyoGe2dxF0g29ODm1eGI',
    appId: '1:138811229758:ios:2e1ae7fcc9bfe6a3ae336f',
    messagingSenderId: '138811229758',
    projectId: 'gajeep-c5101',
    databaseURL: 'https://gajeep-c5101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gajeep-c5101.appspot.com',
    iosClientId: '138811229758-3v92on44e6inn9qfid9j8h7v3vjb317b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA-OoRnuxa_4qTyoGe2dxF0g29ODm1eGI',
    appId: '1:138811229758:ios:2e1ae7fcc9bfe6a3ae336f',
    messagingSenderId: '138811229758',
    projectId: 'gajeep-c5101',
    databaseURL: 'https://gajeep-c5101-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gajeep-c5101.appspot.com',
    iosClientId: '138811229758-3v92on44e6inn9qfid9j8h7v3vjb317b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp1',
  );
}
